### PR TITLE
New theme 

### PR DESCRIPTION
**Pull request by dimitraz**
## Notes 
- Needs lots of work but its a start 
- Please add me as a contributor so I can push directly 
- Please give me access to CMS itself so I can edit the podcasts page, as per mockups the soundcloud episodes should be embedded individually with titles above them

### Home page
Screenshot 2019-12-12 at 23 58 46

### Post page
Screenshot 2019-12-13 at 00 01 17

### Podcasts page
Todo

### CODE REVIEW

**Comment by marcotroisi** [comment]
Deploy preview: https://deploy-preview-2--londonandnewcastle.netlify.com/

**Review by marcotroisi — APPROVED** [review]

**Comment by alezucca** [comment]
image

**Comment by dimitraz** [comment]
Hi @alezucca @milenazuccarelli , can you take a look at the deploy preview and highlight some areas we want to address, I can work on it in the next few days

**Comment by dimitraz** [comment]
We can merge this in the meantime if you want

**Comment by alezucca** [comment]
Hi Dimitra,
I really like everything so far. Would just say images on home page, read
more button, and some edits to the podcast page!
Thank you!!!!

**Pull request merged**
